server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}
  queue-size: 512

apm:
  url: ${APM_URL:http://localhost:8200}
  logLevel: info
  usePathAsTransactionName: true
  transactionNameGroups: GET /resources/*,PUT /resources/permanent/*

monitoring:
  uri: ${KIBANA_URI:http://localhost:5601}